//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyToDoManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskUser
    {
        public int TaskId { get; set; }
        public string UserId { get; set; }
        public int TaskUserMapId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
